name: Sync 404 with index

on:
  push:
    paths:
      - "index.html"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy index.html to 404.html
        run: cp index.html 404.html

      - name: Commit 404.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add 404.html
          git commit -m "sync 404.html with index.html" || echo "No changes"
          git push
